CREATE TABLE PRODUCT
(
    ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    PRICE DOUBLE NOT NULL,
    CATEGORY VARCHAR(20) NOT NULL,
    INGREDIENTS VARCHAR(200) NOT NULL,
    PROTEIN DOUBLE NOT NULL,
    FAT DOUBLE NOT NULL,
    CARBOHYDRATE DOUBLE NOT NULL,
    CALORICITY DOUBLE NOT NULL,
    WEIGHT INT NOT NULL,
    PIC_ID VARCHAR(100) NOT NULL
);
CREATE UNIQUE INDEX PRODUCT_ID_uindex ON PRODUCT (ID)

