CREATE TABLE PRODUCT
(
    ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    PRICE DOUBLE NOT NULL,
    CATEGORY VARCHAR(20) NOT NULL,
    INGREDIENTS VARCHAR(200) NOT NULL,
    PROTEIN DOUBLE NOT NULL,
    FAT DOUBLE NOT NULL,
    CARBOHYDRATE DOUBLE NOT NULL,
    CALORICITY DOUBLE NOT NULL,
    WEIGHT INT NOT NULL,
    PIC_ID VARCHAR(100) NOT NULL
);
CREATE UNIQUE INDEX PRODUCT_ID_uindex ON PRODUCT (ID);

CREATE TABLE USER
(
    ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    CHAT_ID INT NOT NULL,
    PHONE_NUMBER VARCHAR(15),
    CALORICITY_LIMIT DOUBLE
);
CREATE UNIQUE INDEX USER_ID_uindex ON USER (ID);


CREATE TABLE "ORDER"
(
    ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    DATE DATE NOT NULL,
    CONSTRAINT ORDER_PRODUCT_ID_fk FOREIGN KEY (ID) REFERENCES PRODUCT (ID),
    CONSTRAINT ORDER_USER_ID_fk FOREIGN KEY (ID) REFERENCES USER (ID)
);
CREATE UNIQUE INDEX ORDER_ID_uindex ON "ORDER" (ID);



INSERT INTO PUBLIC.PRODUCT (ID, NAME, PRICE, CATEGORY, INGREDIENTS, PROTEIN, FAT, CARBOHYDRATE, CALORICITY, WEIGHT, PIC_ID) VALUES (1001, 'Суп східний з броколі', 66, 'перші страви', 'броколі, горох, сочевиця, спеції в асортименті, вершки 26 %, сіль, зелень в асортименті (кріп, петрушка, цибуля зел)', 55.5, 28.4, 23.1, 215.17, 250, 'AgADAgADkagxG5slUUvhRjYpQPzQ0M_9Mg4ABEBBe4UMjXen7T0DAAEC');
INSERT INTO PUBLIC.PRODUCT (ID, NAME, PRICE, CATEGORY, INGREDIENTS, PROTEIN, FAT, CARBOHYDRATE, CALORICITY, WEIGHT, PIC_ID) VALUES (2001, 'Філе білої риби на томатній подушці', 87, 'основні страви', 'філе мерлузи, морква, кабачок, вершки, томатний соус, кріп, лимон', 100.5, 45.4, 54.1, 287.17, 350, 'AgADAgADp6gxG5slUUvM5oOc3JRURvIDnA4ABDeF5KJuAbZVh5wAAgI');
INSERT INTO PUBLIC.PRODUCT (ID, NAME, PRICE, CATEGORY, INGREDIENTS, PROTEIN, FAT, CARBOHYDRATE, CALORICITY, WEIGHT, PIC_ID) VALUES (3001, 'Кіш лорен', 90, 'основні страви', 'пісочне тісто (пшеничне борошно, вершкове масло, яйця, сіль), твердий сир, вершки, шинка, бекон, цибуля - порей', 90.5, 99.4, 124.1, 341.17, 200, 'AgADAgADqKgxG5slUUsi9s8MvpCZoqn_Mg4ABA3XiuwQ4uKLgjsDAAEC');
INSERT INTO PUBLIC.PRODUCT (ID, NAME, PRICE, CATEGORY, INGREDIENTS, PROTEIN, FAT, CARBOHYDRATE, CALORICITY, WEIGHT, PIC_ID) VALUES (4001, 'Наполеон десерт', 42, 'десерти', 'листкове тісто, білий шоколад, яєчний жовток, цукор, вершкове масло', 71.2, 153.4, 90.1, 247.8, 150, 'AgADAgADqagxG5slUUtZG8_TiTrcmmwGnA4ABIxRYBCzz9ISk5cAAgI');

